### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by donschriefer** [Decarb/beam-me-up#1]
There are some lazy habits of missing documentation for the accompanying code. How am I supposed to know what you were thinking when you were writing this thing?

**Comment by decarb** [comment]
I guess one shouldn't open up issues for missing docs. 😆 

I do want to add docs in the future but for now it's definitely not necessary. I'm assuming that someone contributing to the code will know how to read it. I tried to write it in such a way that they can.
